apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ .Values.externalSecrets.target.name }}
    creationPolicy: {{ .Values.externalSecrets.target.creationPolicy }}
  data:
    - secretKey: {{ .Values.externalSecrets.data.secretKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.data.remoteRef.key }}
        property: {{ .Values.externalSecrets.data.remoteRef.property }}
